# Generated by Django 6.0.2 on 2026-03-02 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default='12:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('slot_interval_minutes', models.IntegerField(default=60, help_text='Minutes between bookable slots')),
                ('reservation_duration_minutes', models.IntegerField(default=90, help_text='Duration of each reservation in minutes')),
            ],
            options={
                'verbose_name': 'Restaurant Schedule',
                'verbose_name_plural': 'Restaurant Schedule',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('cancel_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.table')),
            ],
            options={
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['date', 'status'], name='reservation_date_b616a1_idx'), models.Index(fields=['cancel_code'], name='reservation_cancel__07da5f_idx')],
            },
        ),
    ]
